GET http://localhost:8080/blog-posts

### put request with sample blog
POST http://localhost:8080/blog-posts
Content-Type: application/json
 
{
  "title": "Finally endpoints work!",
  "content": "I'm so happy I think I finally got the hang of these mongodb endpoints :)",
  "author": {
    "firstName": "Julia",
    "lastName": "Finarovsky"
  }
}

### get request with query

GET http://localhost:8080/blog-posts?author=Billy%20Smith


### get reqest with id

GET http://localhost:8080/blog-posts/58ec4d9e1aba1c1fe81518a6


### get request with wrong id

GET http://localhost:8080/blog-posts/58c4de1aba1c1f1518a6

### delete request with id
DELETE http://localhost:8080/blog-posts/58ec67165748a752ac06a958

### put request
PUT http://localhost:8080/blog-posts/58ed911c5a101e13bc3184c2
Content-Type: application/json
 
{
  "id" : "58ed911c5a101e13bc3184c2",
  "title": "Try not null",
  "content": "How about some actual content"
  
}